apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8s-workload-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: webhook
  name: webhook-manager
  namespace: system
  annotations:
    description: "Service account for kcloud-operator webhook manager"
    kubernetes.io/service-account.name: "webhook-manager"
