# This rule is not used by the project k8s-workload-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.keti.kcloud.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-workload-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadoptimizer-editor-role
rules:
- apiGroups:
  - apps.keti.kcloud
  resources:
  - workloadoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.keti.kcloud
  resources:
  - workloadoptimizers/status
  verbs:
  - get
