# This rule is not used by the project k8s-workload-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.keti.kcloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-workload-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadoptimizer-admin-role
rules:
- apiGroups:
  - apps.keti.kcloud
  resources:
  - workloadoptimizers
  verbs:
  - '*'
- apiGroups:
  - apps.keti.kcloud
  resources:
  - workloadoptimizers/status
  verbs:
  - get
