apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8s-workload-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: controller
  name: controller-manager
  namespace: system
  annotations:
    description: "Service account for kcloud-operator controller manager"
    kubernetes.io/service-account.name: "controller-manager"
